set nocompatible
syntax on
filetype plugin indent on

let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set termguicolors
colorscheme matts-green

set number
set cursorline
set signcolumn=yes
set scrolloff=8
set nowrap

set tabstop=4
set shiftwidth=4
set expandtab
set smartindent

set ignorecase
set smartcase
set incsearch
set hlsearch

set splitbelow
set splitright
set hidden
set laststatus=2

set backspace=indent,eol,start
set mouse=a
