# Development infrastructure for Artificer microservices
# Industry standard: Simple, shared services for development

version: '3.8'

services:
  # Shared Redis for development (all services can use this)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # Basic configuration - no custom config files needed
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru

  # Redis UI for development debugging (optional)
  redis-ui:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  redis_data:
