services:
  grafana:
    image: grafana/grafana:latest
    container_name: algo-trader-grafana
    ports:
      - "3000:3000"
    environment:
      # Disable authentication for localhost development
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_INSTALL_PLUGINS=
    volumes:
      - ./system/algo_trader/grafana:/etc/grafana/provisioning/dashboards
      - grafana-storage:/var/lib/grafana
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  grafana-storage:
    driver: local

