[tool.uv]
package = true

[project]
name = "artificer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
artificer = "artificer.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
