# Redis Cluster for Production Environment
# High availability, persistent, scalable Redis setup

version: '3.8'

services:
  # Redis Cluster Nodes
  redis-node-1:
    image: redis:7.2-alpine
    container_name: redis-cluster-node-1
    ports:
      - "7000:6379"
      - "17000:16379"
    volumes:
      - redis_node_1_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf --cluster-enabled yes --cluster-config-file nodes-6379.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - redis-cluster

  redis-node-2:
    image: redis:7.2-alpine
    container_name: redis-cluster-node-2
    ports:
      - "7001:6379"
      - "17001:16379"
    volumes:
      - redis_node_2_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf --cluster-enabled yes --cluster-config-file nodes-6379.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - redis-cluster

  redis-node-3:
    image: redis:7.2-alpine
    container_name: redis-cluster-node-3
    ports:
      - "7002:6379"
      - "17002:16379"
    volumes:
      - redis_node_3_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf --cluster-enabled yes --cluster-config-file nodes-6379.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - redis-cluster

  # Redis Sentinel for High Availability
  redis-sentinel-1:
    image: redis:7.2-alpine
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf:ro
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
    networks:
      - redis-cluster

  # Monitoring
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis-node-1:6379
    depends_on:
      - redis-node-1
    networks:
      - redis-cluster

volumes:
  redis_node_1_data:
    driver: local
  redis_node_2_data:
    driver: local
  redis_node_3_data:
    driver: local

networks:
  redis-cluster:
    driver: bridge
