
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- external monitor at home (1080p 165Hz) - catch-all, sits on top
hl.monitor({
    output   = "",
    mode     = "1920x1080@165.00",
    position = "0x0",
    scale    = "auto",
})

-- work ultrawide (Samsung C34H89x) - overrides the wildcard above, sits on top
hl.monitor({
    output   = "desc:Samsung Electric Company C34H89x HCJTA03681",
    mode     = "3440x1440@99.98",
    position = "0x0",
    scale    = "1",
})

-- laptop screen - centered below the work ultrawide ((3440-1920)/2 = 760)
-- NOTE: 760 offset is specific to the ultrawide; revisit for the home setup
hl.monitor({
    output   = "eDP-1",
    mode     = "preferred",
    position = "760x1440",
    scale    = "2",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "alacritty"
local fileManager = "dolphin"
local menu        = "rofi -show drun"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
-- hl.on("hyprland.start", function ()
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox")
-- end)

hl.on("hyprland.start", function ()
  hl.exec_cmd("hyprpaper")
  hl.exec_cmd("waybar")
  hl.exec_cmd("wl-paste --watch cliphist store")
  hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE && systemctl --user start hypridle.service")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_THEME",    "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE",     "24")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("HYPRCURSOR_SIZE",  "24")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 3,
        gaps_out = 8,

        border_size = 3,

        col = {
            active_border   = { colors = {"rgba(e0631fee)", "rgba(3c6b5eee)"}, angle = 45 },
            inactive_border = "rgba(24332eaa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "scrolling",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        repeat_delay = 150, -- ms held before a key starts repeating
        repeat_rate  = 35,  -- repeats per second

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.config({
    cursor = {
        inactive_timeout = 5, -- hide the cursor after 5s of no movement
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal)) -- keybind: SUPER+Return|Open terminal (alacritty)
local closeWindowBind = hl.bind(mainMod .. " + W", hl.dsp.window.close()) -- keybind: SUPER+W|Close active window
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'")) -- keybind: SUPER+M|Exit Hyprland session
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager)) -- keybind: SUPER+E|Open file manager (dolphin)
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" })) -- keybind: SUPER+V|Toggle floating on active window
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(menu)) -- keybind: SUPER+D|Open app launcher (rofi drun)
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo()) -- keybind: SUPER+P|Toggle pseudotile on active window

-- Keybind cheatsheet: floating alacritty running the shortcuts script; any key dismisses it (handled in the script).
hl.bind(mainMod .. " + SHIFT + slash", hl.dsp.exec_cmd("alacritty --class cheatsheet -e python3 ~/Artificer/apps/shortcuts/shortcuts.py")) -- keybind: SUPER+SHIFT+slash|Keybind cheatsheet (press any key to dismiss)

-- Scrolling-layout window sizing
hl.bind(mainMod .. " + F",         hl.dsp.layout("colresize 1.0"))    -- keybind: SUPER+F|Maximize focused window to full width
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen())        -- keybind: SUPER+SHIFT+F|True fullscreen
hl.bind(mainMod .. " + minus",     hl.dsp.layout("colresize -0.1"))   -- keybind: SUPER+minus|Shrink column width
hl.bind(mainMod .. " + equal",     hl.dsp.layout("colresize +0.1"))   -- keybind: SUPER+equal|Grow column width
hl.bind(mainMod .. " + R",         hl.dsp.layout("colresize +conf"))  -- keybind: SUPER+R|Cycle preset column widths
hl.bind(mainMod .. " + C",         hl.dsp.layout("center"))           -- keybind: SUPER+C|Center active column

-- Move focus with mainMod + hjkl
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" })) -- keybind: SUPER+H|Focus window left
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" })) -- keybind: SUPER+L|Focus window right
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" })) -- keybind: SUPER+K|Focus window up
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" })) -- keybind: SUPER+J|Focus window down

-- Move window with mainMod + SHIFT + hjkl (mirror of the focus binds above)
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.layout("consume_or_expel prev")) -- keybind: SUPER+SHIFT+H|Move window left (join column / split back out)
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.layout("consume_or_expel next")) -- keybind: SUPER+SHIFT+L|Move window right (join column / split back out)
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "up" }))    -- keybind: SUPER+SHIFT+K|Move window up
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "down" }))  -- keybind: SUPER+SHIFT+J|Move window down

-- Move the current workspace to the monitor in a direction (mirror of hjkl, with CTRL)
hl.bind(mainMod .. " + CTRL + H", hl.dsp.workspace.move({ monitor = "l" })) -- keybind: SUPER+CTRL+H|Move workspace to monitor left
hl.bind(mainMod .. " + CTRL + L", hl.dsp.workspace.move({ monitor = "r" })) -- keybind: SUPER+CTRL+L|Move workspace to monitor right
hl.bind(mainMod .. " + CTRL + K", hl.dsp.workspace.move({ monitor = "u" })) -- keybind: SUPER+CTRL+K|Move workspace to monitor up
hl.bind(mainMod .. " + CTRL + J", hl.dsp.workspace.move({ monitor = "d" })) -- keybind: SUPER+CTRL+J|Move workspace to monitor down

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i})) -- keybind: SUPER+[0-9]|Switch to workspace N (0=10)
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i })) -- keybind: SUPER+SHIFT+[0-9]|Move active window to workspace N (0=10)
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic")) -- keybind: SUPER+S|Toggle special workspace (magic scratchpad)
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" })) -- keybind: SUPER+SHIFT+S|Move active window to special workspace (magic)

-- Obsidian scratchpad: start it on first use, then toggle it in/out of view.
-- hyprctl dispatch takes a Lua expression in this config, hence the hl.dsp.* args.
hl.bind(mainMod .. " + N",
    hl.dsp.exec_cmd([[hyprctl clients | grep -q 'class: obsidian' || hyprctl dispatch 'hl.dsp.exec_cmd("obsidian")'; hyprctl dispatch 'hl.dsp.workspace.toggle_special("notes")']])) -- keybind: SUPER+N|Obsidian scratchpad (launch / toggle, floating)

-- Yazi: spawn a new terminal running yazi.
hl.bind(mainMod .. " + Y", hl.dsp.exec_cmd(terminal .. " -e yazi")) -- keybind: SUPER+Y|Open yazi in a new terminal

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" })) -- keybind: SUPER+ScrollDown|Focus next workspace
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" })) -- keybind: SUPER+ScrollUp|Focus previous workspace

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true }) -- keybind: SUPER+LMB|Drag to move window
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true }) -- keybind: SUPER+RMB|Drag to resize window

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

-- Screen lock (hyprlock), screenshots (grim + slurp), clipboard history (cliphist)
hl.bind(mainMod .. " + X",         hl.dsp.exec_cmd("hyprlock"))                                                                                    -- keybind: SUPER+X|Lock screen (hyprlock)
hl.bind("Print",                   hl.dsp.exec_cmd([[grim -g "$(slurp)" - | wl-copy]]))                                                            -- keybind: Print|Screenshot region to clipboard
hl.bind("SHIFT + Print",           hl.dsp.exec_cmd("grim - | wl-copy"))                                                                            -- keybind: SHIFT+Print|Screenshot whole screen to clipboard
hl.bind(mainMod .. " + Print",     hl.dsp.exec_cmd([[mkdir -p ~/Pictures/Screenshots && grim -g "$(slurp)" ~/Pictures/Screenshots/$(date +%Y%m%d_%H%M%S).png]])) -- keybind: SUPER+Print|Screenshot region to file (~/Pictures/Screenshots)
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd([[cliphist list | rofi -dmenu | cliphist decode | wl-copy]]))                                   -- keybind: SUPER+SHIFT+V|Clipboard history (cliphist via rofi)


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

-- No permanent workspaces; nothing is routed or opened at startup.

-- Keybind cheatsheet (SUPER+SHIFT+slash): float it centered, sized to roughly
-- half the screen. Matches the --class passed to alacritty in the bind above.
hl.window_rule({
    name  = "cheatsheet",
    match = { class = "cheatsheet" },
    float = true,
    size  = "monitor_w*0.5 monitor_h*0.6",
    move  = "monitor_w*0.25 monitor_h*0.2",
})

-- Obsidian scratchpad: whenever Obsidian opens it floats onto a dedicated
-- special workspace, toggled in/out of view with SUPER+N.
hl.window_rule({
    name  = "obsidian-scratch",
    match = { class = "obsidian" },
    workspace = "special:notes silent",
    float = true,
    size  = "monitor_w*0.6 monitor_h*0.85",
    move  = "monitor_w*0.2 monitor_h*0.075",
})
