preload = /home/matthew/Artificer/utils/hypr/wallpapers/dead-world.jpg

wallpaper {
    monitor = DP-3
    path = /home/matthew/Artificer/utils/hypr/wallpapers/dead-world.jpg
}

splash = false
ipc = on
