load("@pip//:requirements.bzl", "requirement")

py_library(
    name = "stock",
    srcs = ["stock.py"],
    deps = [
        requirement("pydantic"),
    ],
    visibility = ["//visibility:public"],
)
