py_library(
    name = "redis_services",
    srcs = ["account.py"],
    visibility = [
        "//system/algo_trader:__subpackages__",
        "//tests:__subpackages__",
        "//system:__pkg__",
    ],
    deps = [
        "//infrastructure/redis:redis",
    ],
)
