py_library(
    name = "client",
    srcs = [
        "client.py",
    ],
    deps = [
        "//infrastructure/logging:logger",
    ],
    visibility = [
        "//infrastructure/client:__subpackages__",
    ],
)