load("@pip//:requirements.bzl", "requirement")

py_library(
    name = "schema",
    srcs = ["schema.py"],
    deps = [
        requirement("pydantic"),
    ],
    visibility = ["//visibility:public"],
)
