"""Signal writer for strategy execution.

This module provides functionality to write trading signals generated by
strategies to InfluxDB for persistence and analysis.
"""

from datetime import datetime, timezone
from typing import Any

import pandas as pd

from infrastructure.logging.logger import get_logger
from system.algo_trader.influx.market_data_influx import MarketDataInflux


class SignalWriter:
    """Writes trading signals to InfluxDB.

    Handles serialization and writing of trading signals generated by strategies
    to InfluxDB for persistence and historical analysis.

    Args:
        influx_client: InfluxDB client instance for writing signals.
        strategy_name: Name of the strategy generating signals.
        logger: Optional logger instance. If not provided, creates a new logger.
        strategy_args: Optional dictionary of strategy arguments to store as tags.
    """

    def __init__(
        self,
        influx_client: MarketDataInflux,
        strategy_name: str,
        logger=None,
        strategy_args: dict[str, Any] | None = None,
    ):
        """Initialize SignalWriter with InfluxDB client.

        Args:
            influx_client: InfluxDB client instance for writing signals.
            strategy_name: Name of the strategy generating signals.
            logger: Optional logger instance. If not provided, creates a new logger.
            strategy_args: Optional dictionary of strategy arguments to store as tags.
        """
        self.influx_client = influx_client
        self.strategy_name = strategy_name
        self.strategy_args = strategy_args
        self.logger = logger or get_logger(self.__class__.__name__)

    def write_signals(self, signals: pd.DataFrame, ticker: str) -> bool:
        """Write trading signals to InfluxDB.

        Serializes signals DataFrame and writes to InfluxDB strategy table
        with proper timestamp formatting and metadata.

        Args:
            signals: DataFrame containing signals with DatetimeIndex and required columns.
            ticker: Ticker symbol associated with the signals.

        Returns:
            True if signals were successfully written, False otherwise.
        """
        if signals.empty:
            self.logger.info(f"No signals to write for {ticker}")
            return True

        required_cols = {"signal_type", "price"}
        if not required_cols.issubset(signals.columns):
            missing = required_cols - set(signals.columns)
            self.logger.error(f"Missing required columns: {missing}")
            return False

        signals_copy = signals.copy()
        signals_copy["ticker"] = ticker
        signals_copy["strategy"] = self.strategy_name
        signals_copy["generated_at"] = datetime.now(timezone.utc).isoformat()

        # Add strategy arguments as columns if provided
        tag_columns = ["ticker", "strategy"]
        if self.strategy_args:
            for key, value in self.strategy_args.items():
                signals_copy[key] = value
                tag_columns.append(key)

        if not isinstance(signals_copy.index, pd.DatetimeIndex):
            self.logger.error("Signals DataFrame must have DatetimeIndex")
            return False

        signals_copy = signals_copy.reset_index()
        if signals_copy.columns[0] != "time":
            signals_copy = signals_copy.rename(columns={signals_copy.columns[0]: "time"})

        signals_copy["datetime"] = pd.to_datetime(signals_copy["time"]).astype("int64") // 10**6
        signals_copy = signals_copy.drop("time", axis=1)

        signal_records = signals_copy.to_dict("records")

        try:
            success = self.influx_client.write(
                data=signal_records, ticker=ticker, table="strategy", tag_columns=tag_columns
            )
            if success:
                self.logger.info(f"Wrote {len(signal_records)} signals for {ticker} to InfluxDB")
            return success
        except Exception as e:
            self.logger.error(f"Failed to write signals for {ticker}: {e}")
            return False
