py_library(
    name = "infra",
    visibility = [
        "//system/algo_trader:__subpackages__",
        "//system:__pkg__",
    ],
    deps = [
        "//system/algo_trader/infra/redis:redis_services",
    ],
)
